version: '3.8'
services:
  dev:
    container_name: auto-marketing-be
    image: loyalty-event/auto-marketing-be:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    depends_on:
      - db
    ports:
      - 5000:5000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    command: yarn start:dev
    # restart: unless-stopped # try this will restart if meet crash, but use pm2 instead
  db:
    image: postgres
    container_name: loyalty-event-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: always
